_wandb:
    value:
        cli_version: 0.23.1
        e:
            x9cgtjqm8aeareeev3yqm3v149ldnmle:
                codePath: hw1/src/hw1_imitation/train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 22
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1003736440832"
                        used: "72037986304"
                email: hengyang@berkeley.edu
                executable: /home/heng/code/homework_spring2026/hw1/.venv/bin/python3
                git:
                    commit: b1ffc4d99055a14ff37f0111204e1eac0f4a6fb0
                    remote: https://github.com/berkeleydeeprlcourse/homework_spring2026.git
                gpu: NVIDIA GeForce RTX 4070 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4070 Laptop GPU
                      uuid: GPU-20c352f4-e4cc-893a-286f-9d9fcd718e51
                host: yang.ch
                memory:
                    total: "33055854592"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/heng/code/homework_spring2026/hw1/src/hw1_imitation/train.py
                python: CPython 3.11.14
                root: /home/heng/code/homework_spring2026/hw1/src/hw1_imitation
                startedAt: "2026-02-12T08:44:51.076065Z"
                writerId: x9cgtjqm8aeareeev3yqm3v149ldnmle
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 128
chunk_size:
    value: 8
data_dir:
    value: data
eval_interval:
    value: 10000
exp_name:
    value: null
flow_num_steps:
    value: 10
hidden_dims:
    value:
        - 256
        - 256
        - 256
log_interval:
    value: 100
lr:
    value: 0.0003
num_epochs:
    value: 400
num_video_episodes:
    value: 5
policy_type:
    value: mse
seed:
    value: 42
video_size:
    value:
        - 256
        - 256
wandb_project:
    value: hw1-imitation
weight_decay:
    value: 0
